# Generated by Django 2.2.4 on 2020-10-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='dojo_id',
        ),
    ]
