# Generated by Django 2.2.4 on 2020-10-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_remove_ninjas_dojo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='dojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ninja', to='dojo_ninjas_app.Dojos'),
        ),
    ]
